# Generated by Django 2.2 on 2020-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DafLearning1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexTypeOfStudy', models.IntegerField()),
                ('masechet', models.TextField(max_length=50)),
                ('pageNumber', models.IntegerField()),
                ('isLearning', models.BooleanField()),
                ('chazara', models.IntegerField()),
                ('isLearningPage1', models.BooleanField()),
                ('isLearningPage2', models.BooleanField()),
                ('typeOfStudy', models.TextField(max_length=50)),
                ('pageDate', models.TextField(max_length=50)),
            ],
        ),
    ]
